ruleDirs: 
  -  dev_rules
  -  lowRISC_rules
testConfigs:
  -  testDir: dev_tests
  -  testDir: lowRISC_tests
customLanguages:
  systemverilog:
    libraryPath: /temp/tree-sitter-systemverilog/systemverilog.so
    extensions: [sv, v]
    expandoChar: _
