name: generate

# https://github.com/tree-sitter/tree-sitter/blob/master/docs/src/cli/generate.md

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ls
        run: ls

      - name: submodule
        #run: git submodule --depth=1 add https://github.com/gmlarumbe/tree-sitter-systemverilog
        run: git clone --depth=1 https://github.com/gmlarumbe/tree-sitter-systemverilog $HOME/tree-sitter-systemverilog
         
      - name: Cache tree-sitter-systemverilog
        uses: actions/cache@v4
        with:
          path: |
            tree-sitter-systemverilog
            .git/modules/tree-sitter-systemverilog
            tree-sitter-systemverilog/build
            tree-sitter-systemverilog/systemverilog.so
          key: ${{ runner.os }}-tree-sitter-systemverilog-${{ hashFiles('tree-sitter-systemverilog/**') }}
          restore-keys: |
            ${{ runner.os }}-tree-sitter-systemverilog-

      # - name: git submodule add tree-sitter-systemverilog
      #   run: |
      #     if [ ! -d tree-sitter-systemverilog ]; then
      #       git submodule add https://github.com/gmlarumbe/tree-sitter-systemverilog
      #     fi

      - name: ls
        run: ls

      - name: Run git status
        id: status
        run: git status

      - name: cd submodule
        run: cd $HOME/tree-sitter-systemverilog
      
      - name: ls
        run: ls

      - name: setup tree-sitter
        uses: tree-sitter/setup-action@v2

      - name: ls
        run: ls

      - name: build dll
        working-directory: $HOME/tree-sitter-systemverilog
        #run: tree-sitter test
        #run:  tree-sitter generate -b --abi 14 --libdir .
        run: |
          if [ ! -f systemverilog.so ]; then
            tree-sitter generate -b --abi 14 --libdir .
          fi

      - name: ls
        working-directory: tree-sitter-systemverilog
        run: ls

      - name: setup ast-grep
        run: npm install --global @ast-grep/cli

      - name: test rules
        run: sg test --skip-snapshot-tests
