name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: myimage:latest
          outputs: type=docker,dest=${{ runner.temp }}/myimage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: ${{ runner.temp }}/myimage.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: ${{ runner.temp }}

      # - name: Load image
      #   run: |
      #     docker load --input ${{ runner.temp }}/myimage.tar
      #     docker image ls -a

      - name: Test
        run: |
          docker load --input ${{ runner.temp }}/myimage.tar
          docker image ls -a
          docker run --rm myimage:latest sh -c '
            tree-sitter init-config
            ls $HOME
            cat /root/.config/tree-sitter/config.json
            ls
            sg test --skip-snapshot-tests -f hello
          '
